version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
