name: Starting example
storage:
  engine: hdf5
  root: network.hdf5
network:
  x: 200
  y: 200
  z: 200
regions:
  brain_region:
    type: stack
    children:
    - base_layer
    - top_layer
partitions:
  base_layer:
    type: layer
    thickness: 100
  top_layer:
    type: layer
    thickness: 100
cell_types:
  base_type:
    spatial:
      radius: 2.5
      density: 3.9e-4
  top_type:
    spatial:
      radius: 7
      count: 40
placement:
  example_placement:
    strategy: bsb.placement.RandomPlacement
    cell_types:
    - base_type
    partitions:
    - base_layer
  top_placement:
    strategy: bsb.placement.RandomPlacement
    cell_types:
    - top_type
    partitions:
    - top_layer
connectivity:
  A_to_B:
    strategy: bsb.connectivity.VoxelIntersection
    presynaptic:
      cell_types:
      - base_type
    postsynaptic:
      cell_types:
      - top_type
simulations:
  basal_activity:
    simulator: nest
    resolution: 0.1
    duration: 5000
    cell_models:
      base_type:
        model: iaf_cond_alpha
      top_type:
        model: aeif_cond_alpha
    connection_models:
      A_to_B:
        synapse:
          model: static_synapse
          weight: 300
          delay: 1
    devices:
      background_noise:
        device: poisson_generator
        rate: 10
        targetting:
          strategy: cell_model
          cell_models:
          - base_type
        weight: 40
        delay: 10
      base_layer_record:
        device: spike_recorder
        delay: 0.1
        targetting:
          strategy: cell_model
          cell_models:
          - base_type
      top_layer_record:
        device: spike_recorder
        delay: 0.1
        targetting:
          strategy: cell_model
          cell_models:
          - top_type
