name: Mirror to Ebrains

on:
  push:
    branches: [ main, sync ]

jobs:
  ebrains_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: sync_main
        uses: wei/git-sync@v3
        with:
          source_repo: dbbs-lab/bsb
          source_branch: main
          destination_repo: https://push:glpat-xPiEEVo-3ErXjqRxW5M5@gitlab.ebrains.eu/robinde/bsb.git
          destination_branch: main
