name: Mirror to Ebrains

on:
  push:
    branches: [ main, sync ]

jobs:
  ebrains_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Leak secret!
        with:
          BIG_SECRET: ${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}
        run: |
          python -c "import sys; print(*reversed(sys.argv[1]))" $BIG_SECRET
      - name: sync_main
        uses: wei/git-sync@v3
        with:
          source_repo: dbbs-lab/bsb
          source_branch: main
          destination_repo: https://push:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/robinde/bsb.git
          destination_branch: main