name: Bump version, create release and deploy

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.next }}
      old_tag: ${{ steps.semver.outputs.current }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: Update __init__.py and pyproject.toml
        run: |
          replacev="\"${{steps.semver.outputs.next}}\""
          newtag=$(echo $replacev | sed "s/v//g")
          sed -i  "s/__version__ = .*/__version__ = $newtag/g" bsb/__init__.py

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Bump version in Python project
        run: |
          pip install --upgrade pip bump-my-version
          oldv="${{ steps.semver.outputs.current }}"
          newv="${{steps.semver.outputs.next}}"
          # Bump the version, dropping the leading `v` with `${x:1}`
          bump-my-version replace --current-version=${oldv:1} --new-version=${newv:1} pyproject.toml

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.semver.outputs.next }}
          github_token: ${{ github.token }}

  release:
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull commit of version change
        run: |
          git pull origin main 

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ needs.bump.outputs.tag }}
          toTag: ${{ needs.bump.outputs.old_tag }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ needs.bump.outputs.tag }}
          name: ${{ needs.bump.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

  deploy:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          twine upload --verbose --repository pypi dist/*
